name : CI-PIPELINE

on : push

jobs:
  test_pipeline:
    runs-on : ubuntu-latest

    steps:
      - name : code checkout
        uses : actions/checkout@v3
      - name : setup python
        uses : actions/setup-python@v2
      - name : install dependencies
        run : |
          pip install requirements.txt
      - name : run pipeline
        run : |
          dvc repro
