name : CI-PIPELINE

on : push

jobs:
  test_pipeline:
    runs-on : ubuntu-latest

    steps:
      - name : code checkout
        uses : actions/checkout@v3
      - name : setup python
        uses : actions/setup-python@v2
      - name : install dependencies
        run : |
          pip install -r requirements.txt
      - name : run pipeline
        env :
          DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run : |
          dvc repro
      
      - name : test_model_loading
        env : 
          DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run : |
          python tests/test_model_loading.py
      
      - name : test_model_signature
        env : 
          DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run : |
          python tests/test_model_signature.py

      - name : test_model_performance
        env :
          DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run : |
          python tests/test_model_performance.py
          

  

